export const types = Object.freeze({
    // Sync
    BOOKS_START_FETCHING: 'BOOKS_START_FETCHING',
    BOOKS_STOP_FETCHING: 'BOOKS_STOP_FETCHING',
    BOOKS_FILL: 'BOOKS_FILL',
    BOOKS_SET_FETCHING_ERROR: 'BOOKS_SET_FETCHING_ERROR',
    // Async
    BOOKS_FETCH_ASYNC: 'BOOKS_FETCH_ASYNC',
});
